/** Question of the day — same question for both of you, a new one every day. */
export const QUESTIONS = [
  "What song reminds you of us?",
  "What's one small thing I do that makes your day better?",
  "If we could teleport anywhere for dinner tonight, where would we go?",
  "What's a memory of us you replay in your head?",
  "Which movie should we watch together next?",
  "What's something you've never told me but want to?",
  "What was your first impression of me?",
  "What's your comfort food after a long day?",
  "If our story was a film, what would it be called?",
  "What's one thing you want us to try this year?",
  "Which song would you dedicate to me right now?",
  "What's the best trip you've ever taken?",
  "What made you smile today?",
  "Chai or coffee — and why is it chai? ☕",
  "What's a habit of mine you secretly find cute?",
  "What's your dream weekend with me?",
  "What's one thing you're proud of this week?",
  "Which three songs would be on our road-trip playlist?",
  "What's something that always makes you laugh?",
  "If you could relive one day with me, which one?",
  "What's a place in India you want us to visit together?",
  "What's your love language?",
  "What's the most random thing you've googled lately?",
  "Describe us in three emojis.",
  "What's a song you had on repeat as a kid?",
  "What do you want to be doing five years from now?",
  "What's your favourite thing about our chats?",
  "Which festival is your favourite, and why?",
  "What's a small goal we could do together this month?",
  "What's the sweetest thing someone has done for you?",
  "Which singer's voice do you never get tired of?",
  "Beach or mountains for our next trip?",
  "What's one thing you'd like me to know about your day today?",
  "What's your go-to karaoke song?",
  "What would our perfect Sunday look like?",
  "What's a food you want us to cook together?",
  "What's something you're looking forward to?",
  "Which song makes you want to dance instantly?",
  "What did you dream about recently?",
  "What's your favourite photo of us, and why?",
  "Rain or sunshine?",
  "What would you name our pet?",
  "What's a movie line you quote all the time?",
  "What's one thing you'd change about your routine?",
  "What song should play when we see each other next?",
  "What's your favourite time of day to talk to me?",
  "What's a compliment you'll never forget?",
  "What's a song that feels like a hug?",
  "If we started a small business together, what would it be?",
  "What's a tiny win you had today?",
];

export function questionOfTheDay(now = new Date()) {
  const day = Math.floor(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()) / 86_400_000);
  return { key: String(day), text: QUESTIONS[day % QUESTIONS.length] };
}
